version: '3.5'
services:
    djangoapp:
        build: ./docker/python
        command: gunicorn application.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
            - ./files/static_volume:/usr/src/app/static
            - ./files/media_volume:/usr/src/app/media
        networks:
            - nginx_network
            - database_network
        depends_on: 
            - database

    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./application:/var/www/html
            - ./logs:/var/log/nginx
            - ./files/static_volume:/usr/src/app/static
            - ./files/media_volume:/usr/src/app/media
        depends_on:
            - djangoapp
        networks:
            - nginx_network

    database: 
        image: postgres:10
        env_file: 
            - ./database/config/.database_env
        ports:
            - "5432:5432"
        networks:  
            - database_network
        volumes:
            - ./database/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: djangoapps
networks:  
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database:
  static_volume:
  media_volume: